### ISSUE TITLE
问问大家关于争上游答题

### ISSUE THREAD

**Issue by Gingmzmzx** [Gingmzmzx/auto-xuexiqiangguo#3]
我的一个想法是将争上游答题中所有答到的题储存在一个文件里，当积攒到一定量的时候，就可以实现100%正确率。但强国不会更新题库吗？

**Comment by mask0720** [comment]
题库当然会更新的，没有官方题库，但网上有人在整理并同步更新。

**Comment by szsyzx** [comment]
老大您的新版本搞定了吗

**Comment by 85524365** [comment]
支持一下

**Comment by Gingmzmzx** [comment]
v2.3.0公测已经开始了，访问[http://xzy.free.idcfengye.com/web/xxqg/](url)参加内测

**Comment by sanjinxianfeng** [comment]
> v2.3.0公测已经开始了，访问[http://xzy.free.idcfengye.com/web/xxqg/](url)参加内测
已经参加公测，1600 720分辨率的机器不行、

**Comment by Gingmzmzx** [comment]
@sanjinxianfeng 请问您的问题是出在第几步上，申请无障碍权限，截屏，还是执行中出现问题？

**Comment by whhxmwhh** [comment]
启动后。就在刷我的积分页面。没有往下走。旧的版本我现在正在测试。

**Comment by szsyzx** [comment]
我的是打开强国后再主界面就不动了

**Comment by szsyzx** [comment]
小米9 分辨率 2340*1080

**Comment by Gingmzmzx** [comment]
原因是我用来开发的手机上的学习强国版本有点低，我会很快改

**Comment by sanjinxianfeng** [comment]
> @sanjinxianfeng 请问您的问题是出在第几步上，申请无障碍权限，截屏，还是执行中出现问题？

第一步第二部 点击后均可以跳转到相应操作，按要求允许通过后，点击第三步 跳转到学习强国app后，在首页停留无任何动作，到达不了答题界面
